services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports: [ "9200:9200" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 60

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      es:
        condition: service_healthy
    ports: [ "5601:5601" ]