spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres                              # DB_USER
    password: 1111                            # DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:27017/mydb
      # MONGO_INITDB_ROOT_USERNAME=root
      # MONGO_INITDB_ROOT_PASSWORD=rootpassword
      # MONGO_INITDB_DATABASE=mydb

    redis:
      host: localhost
      port: 6379
      password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3600000   # 1시간 (밀리초 단위)

cloud:
  openfeign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: FULL

oauth:
  google:
    android:
      client-id: 1234567890-android.apps.googleusercontent.com
      redirect-uri: com.myapp.android:/oauth2redirect
    ios:
      client-id: 1234567890-ios.apps.googleusercontent.com
      redirect-uri: com.myapp.ios:/oauth2redirect
    web:
      client-id: 1234567890-web.apps.googleusercontent.com
      client-secret: web-client-secret-123456
      redirect-uri: http://localhost:8080/login/oauth2/code/google

  apple:
    team-id: MYTEAMID123
    key-id: MYAPPLEKEY123
    client-id: com.myapp.service
    redirect-uri: http://localhost:8080/login/oauth2/code/apple
    private-key-pem: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASC...
      -----END PRIVATE KEY-----

ncp:
  s3:
    access-key: NCP_ACCESS_KEY_SAMPLE
    secret-key: NCP_SECRET_KEY_SAMPLE
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    bucket: my-ncp-bucket

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG