CREATE TABLE ai_personas (
                             ai_persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             user_id BIGINT NOT NULL,
                             instruction TEXT NOT NULL,
                             background_info TEXT,

                             CONSTRAINT pk_ai_personas PRIMARY KEY (ai_persona_id)
);

COMMENT ON TABLE ai_personas IS 'AI 페르소나 정의';
COMMENT ON COLUMN ai_personas.ai_persona_id IS 'AI 페르소나 ID';
COMMENT ON COLUMN ai_personas.user_id IS '사용자 ID';
COMMENT ON COLUMN ai_personas.instruction IS '시스템 프롬프트 (스크립트)';
COMMENT ON COLUMN ai_personas.background_info IS 'AI가 기억해야 할 배경 지식';