
CREATE TABLE IF NOT EXISTS chat_participant (
    chat_participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatroom_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ,
    last_left_at TIMESTAMPTZ,
    last_read_message_id BIGINT,
    status VARCHAR(255),
    translate_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chat_participant_status_check CHECK (status IN ('ACTIVE', 'LEFT', 'BLOCKED'))
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_chatroom_user'
    ) THEN
        ALTER TABLE chat_participant
        ADD CONSTRAINT uk_chatroom_user UNIQUE (chatroom_id, user_id);
    END IF;
END$$;


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_chatroom'
    ) THEN
        ALTER TABLE chat_participant
        ADD CONSTRAINT fk_chatroom FOREIGN KEY (chatroom_id) REFERENCES chat_room(chatroom_id);
    END IF;
END$$;
