CREATE TABLE main_page_content (
                                   content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title VARCHAR(255) NOT NULL,
                                   html_content TEXT NOT NULL,
                                   original_url VARCHAR(255),
                                   publisher_id BIGINT,
                                   created_at TIMESTAMP(6),
                                   updated_at TIMESTAMP(6)
);

-- 외래키 추가
ALTER TABLE main_page_content
    ADD CONSTRAINT FK_main_page_content_publisher
        FOREIGN KEY (publisher_id)
            REFERENCES users (user_id);