CREATE TABLE post_report (
                             report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             reporter_id BIGINT NOT NULL,
                             reported_user_id BIGINT NOT NULL,
                             post_id BIGINT NOT NULL,

                             post_title_snapshot VARCHAR(255) NOT NULL,
                             post_content_snapshot TEXT NOT NULL,

                             reason_category VARCHAR(255) NOT NULL,
                             reason_detail TEXT,

                             status VARCHAR(255) NOT NULL,
                             created_at TIMESTAMP(6) NOT NULL,

                             CONSTRAINT pk_post_report PRIMARY KEY (report_id),
                             CONSTRAINT uk_reporter_post UNIQUE (reporter_id, post_id),
                             CONSTRAINT fk_post_report_post
                                 FOREIGN KEY (post_id) REFERENCES post (post_id),
                             CONSTRAINT fk_post_report_reporter
                                 FOREIGN KEY (reporter_id) REFERENCES users (user_id),
                             CONSTRAINT fk_post_report_reported_user
                                 FOREIGN KEY (reported_user_id) REFERENCES users (user_id)
);